# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: tools
  licenses: Apache-2.0
  images: |
    - name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r95
apiVersion: v2
appVersion: 4.6.3
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - vista-common
  version: 2.x.x
description: qBittorrent is a cross-platform free and open-source BitTorrent client
home: https://github.com/yidaqiang/helm-charts
icon: https://www.qbittorrent.org/favicon.ico
keywords:
- tools
maintainers:
- name: Vista Yih
  url: https://yidaqiang.github.io/helm-charts
name: qbittorrent
sources:
- https://github.com/qbittorrent/qBittorrent
version: 0.1.0
